/**
 * Institutional Data for F&O Stocks
 * Lot sizes updated for 2026 series
 */

export interface FnoStockInfo {
  symbol: string;
  lotSize: number;
  sector: string;
}

export const FNO_DATA: Record<string, FnoStockInfo> = {
  '360ONE': { symbol: '360ONE', lotSize: 500, sector: 'Financial Services' },
  'ABB': { symbol: 'ABB', lotSize: 125, sector: 'Capital Goods' },
  'APLAPOLLO': { symbol: 'APLAPOLLO', lotSize: 500, sector: 'Consumer Goods' },
  'AUBANK': { symbol: 'AUBANK', lotSize: 1000, sector: 'Banking' },
  'ADANIENSOL': { symbol: 'ADANIENSOL', lotSize: 400, sector: 'Energy' },
  'ADANIENT': { symbol: 'ADANIENT', lotSize: 400, sector: 'Diversified' },
  'ADANIGREEN': { symbol: 'ADANIGREEN', lotSize: 400, sector: 'Energy' },
  'ADANIPORTS': { symbol: 'ADANIPORTS', lotSize: 800, sector: 'Services' },
  'ADANIPOWER': { symbol: 'ADANIPOWER', lotSize: 5000, sector: 'Energy' },
  'ABCAPITAL': { symbol: 'ABCAPITAL', lotSize: 5400, sector: 'Financial Services' },
  'ALKEM': { symbol: 'ALKEM', lotSize: 200, sector: 'Pharma' },
  'AMBER': { symbol: 'AMBER', lotSize: 150, sector: 'Consumer Durables' },
  'AMBUJACEM': { symbol: 'AMBUJACEM', lotSize: 1800, sector: 'Cement' },
  'ANGELONE': { symbol: 'ANGELONE', lotSize: 250, sector: 'Financial Services' },
  'APOLLOHOSP': { symbol: 'APOLLOHOSP', lotSize: 125, sector: 'Healthcare' },
  'ASHOKLEY': { symbol: 'ASHOKLEY', lotSize: 5000, sector: 'Auto' },
  'ASIANPAINT': { symbol: 'ASIANPAINT', lotSize: 200, sector: 'Consumer Goods' },
  'ASTRAL': { symbol: 'ASTRAL', lotSize: 350, sector: 'Consumer Goods' },
  'AUROPHARMA': { symbol: 'AUROPHARMA', lotSize: 1100, sector: 'Pharma' },
  'DMART': { symbol: 'DMART', lotSize: 150, sector: 'Retail' },
  'AXISBANK': { symbol: 'AXISBANK', lotSize: 625, sector: 'Banking' },
  'BSE': { symbol: 'BSE', lotSize: 200, sector: 'Financial Services' },
  'BAJAJ-AUTO': { symbol: 'BAJAJ-AUTO', lotSize: 125, sector: 'Auto' },
  'BAJFINANCE': { symbol: 'BAJFINANCE', lotSize: 125, sector: 'Financial Services' },
  'BAJAJFINSV': { symbol: 'BAJAJFINSV', lotSize: 500, sector: 'Financial Services' },
  'BAJAJHLDNG': { symbol: 'BAJAJHLDNG', lotSize: 50, sector: 'Financial Services' },
  'BANDHANBNK': { symbol: 'BANDHANBNK', lotSize: 2500, sector: 'Banking' },
  'BANKBARODA': { symbol: 'BANKBARODA', lotSize: 4850, sector: 'Banking' },
  'BANKINDIA': { symbol: 'BANKINDIA', lotSize: 4000, sector: 'Banking' },
  'BDL': { symbol: 'BDL', lotSize: 800, sector: 'Capital Goods' },
  'BEL': { symbol: 'BEL', lotSize: 1900, sector: 'Capital Goods' },
  'BHARATFORG': { symbol: 'BHARATFORG', lotSize: 500, sector: 'Capital Goods' },
  'BHEL': { symbol: 'BHEL', lotSize: 5250, sector: 'Energy' },
  'BPCL': { symbol: 'BPCL', lotSize: 1800, sector: 'Energy' },
  'BHARTIARTL': { symbol: 'BHARTIARTL', lotSize: 950, sector: 'Telecom' },
  'BIOCON': { symbol: 'BIOCON', lotSize: 2500, sector: 'Pharma' },
  'BLUESTARCO': { symbol: 'BLUESTARCO', lotSize: 400, sector: 'Consumer Durables' },
  'BOSCHLTD': { symbol: 'BOSCHLTD', lotSize: 50, sector: 'Auto' },
  'BRITANNIA': { symbol: 'BRITANNIA', lotSize: 200, sector: 'FMCG' },
  'CGPOWER': { symbol: 'CGPOWER', lotSize: 900, sector: 'Capital Goods' },
  'CANBK': { symbol: 'CANBK', lotSize: 2250, sector: 'Banking' },
  'CDSL': { symbol: 'CDSL', lotSize: 250, sector: 'Financial Services' },
  'CHOLAFIN': { symbol: 'CHOLAFIN', lotSize: 625, sector: 'Financial Services' },
  'CIPLA': { symbol: 'CIPLA', lotSize: 650, sector: 'Pharma' },
  'COALINDIA': { symbol: 'COALINDIA', lotSize: 2100, sector: 'Energy' },
  'COCHINSHIP': { symbol: 'COCHINSHIP', lotSize: 400, sector: 'Capital Goods' },
  'COFORGE': { symbol: 'COFORGE', lotSize: 375, sector: 'IT' },
  'COLPAL': { symbol: 'COLPAL', lotSize: 350, sector: 'FMCG' },
  'CAMS': { symbol: 'CAMS', lotSize: 200, sector: 'Financial Services' },
  'CONCOR': { symbol: 'CONCOR', lotSize: 1000, sector: 'Services' },
  'CROMPTON': { symbol: 'CROMPTON', lotSize: 1800, sector: 'Consumer Durables' },
  'CUMMINSIND': { symbol: 'CUMMINSIND', lotSize: 300, sector: 'Capital Goods' },
  'DLF': { symbol: 'DLF', lotSize: 1650, sector: 'Realty' },
  'DABUR': { symbol: 'DABUR', lotSize: 1250, sector: 'FMCG' },
  'DALBHARAT': { symbol: 'DALBHARAT', lotSize: 250, sector: 'Cement' },
  'DELHIVERY': { symbol: 'DELHIVERY', lotSize: 1500, sector: 'Services' },
  'DIVISLAB': { symbol: 'DIVISLAB', lotSize: 150, sector: 'Pharma' },
  'DIXON': { symbol: 'DIXON', lotSize: 50, sector: 'Consumer Durables' },
  'DRREDDY': { symbol: 'DRREDDY', lotSize: 125, sector: 'Pharma' },
  'ETERNAL': { symbol: 'ETERNAL', lotSize: 500, sector: 'Chemicals' },
  'EICHERMOT': { symbol: 'EICHERMOT', lotSize: 175, sector: 'Auto' },
  'EXIDEIND': { symbol: 'EXIDEIND', lotSize: 3600, sector: 'Auto' },
  'FORCEMOT': { symbol: 'FORCEMOT', lotSize: 100, sector: 'Auto' },
  'NYKAA': { symbol: 'NYKAA', lotSize: 2000, sector: 'Retail' },
  'FORTIS': { symbol: 'FORTIS', lotSize: 1300, sector: 'Healthcare' },
  'GAIL': { symbol: 'GAIL', lotSize: 4575, sector: 'Energy' },
  'GMRAIRPORT': { symbol: 'GMRAIRPORT', lotSize: 11250, sector: 'Services' },
  'GLENMARK': { symbol: 'GLENMARK', lotSize: 725, sector: 'Pharma' },
  'GODFRYPHLP': { symbol: 'GODFRYPHLP', lotSize: 150, sector: 'FMCG' },
  'GODREJCP': { symbol: 'GODREJCP', lotSize: 500, sector: 'FMCG' },
  'GODREJPROP': { symbol: 'GODREJPROP', lotSize: 325, sector: 'Realty' },
  'GRASIM': { symbol: 'GRASIM', lotSize: 475, sector: 'Diversified' },
  'HCLTECH': { symbol: 'HCLTECH', lotSize: 700, sector: 'IT' },
  'HDFCAMC': { symbol: 'HDFCAMC', lotSize: 300, sector: 'Financial Services' },
  'HDFCBANK': { symbol: 'HDFCBANK', lotSize: 550, sector: 'Banking' },
  'HDFCLIFE': { symbol: 'HDFCLIFE', lotSize: 1100, sector: 'Financial Services' },
  'HAVELLS': { symbol: 'HAVELLS', lotSize: 500, sector: 'Consumer Goods' },
  'HEROMOTOCO': { symbol: 'HEROMOTOCO', lotSize: 300, sector: 'Auto' },
  'HINDALCO': { symbol: 'HINDALCO', lotSize: 1400, sector: 'Metals' },
  'HAL': { symbol: 'HAL', lotSize: 300, sector: 'Capital Goods' },
  'HINDPETRO': { symbol: 'HINDPETRO', lotSize: 2700, sector: 'Energy' },
  'HINDUNILVR': { symbol: 'HINDUNILVR', lotSize: 300, sector: 'FMCG' },
  'HINDZINC': { symbol: 'HINDZINC', lotSize: 800, sector: 'Metals' },
  'POWERINDIA': { symbol: 'POWERINDIA', lotSize: 50, sector: 'Capital Goods' },
  'HYUNDAI': { symbol: 'HYUNDAI', lotSize: 200, sector: 'Auto' },
  'ICICIBANK': { symbol: 'ICICIBANK', lotSize: 700, sector: 'Banking' },
  'ICICIGI': { symbol: 'ICICIGI', lotSize: 425, sector: 'Financial Services' },
  'ICICIPRULI': { symbol: 'ICICIPRULI', lotSize: 1100, sector: 'Financial Services' },
  'IDFCFIRSTB': { symbol: 'IDFCFIRSTB', lotSize: 7500, sector: 'Banking' },
  'ITC': { symbol: 'ITC', lotSize: 1600, sector: 'FMCG' },
  'INDIANB': { symbol: 'INDIANB', lotSize: 1000, sector: 'Banking' },
  'IEX': { symbol: 'IEX', lotSize: 3750, sector: 'Financial Services' },
  'IOC': { symbol: 'IOC', lotSize: 4850, sector: 'Energy' },
  'IRFC': { symbol: 'IRFC', lotSize: 2500, sector: 'Financial Services' },
  'IREDA': { symbol: 'IREDA', lotSize: 2000, sector: 'Energy' },
  'INDUSTOWER': { symbol: 'INDUSTOWER', lotSize: 1700, sector: 'Telecom' },
  'INDUSINDBK': { symbol: 'INDUSINDBK', lotSize: 500, sector: 'Banking' },
  'NAUKRI': { symbol: 'NAUKRI', lotSize: 150, sector: 'IT' },
  'INFY': { symbol: 'INFY', lotSize: 400, sector: 'IT' },
  'INOXWIND': { symbol: 'INOXWIND', lotSize: 400, sector: 'Energy' },
  'INDIGO': { symbol: 'INDIGO', lotSize: 300, sector: 'Services' },
  'JINDALSTEL': { symbol: 'JINDALSTEL', lotSize: 1250, sector: 'Metals' },
  'JSWENERGY': { symbol: 'JSWENERGY', lotSize: 1250, sector: 'Energy' },
  'JSWSTEEL': { symbol: 'JSWSTEEL', lotSize: 675, sector: 'Metals' },
  'JIOFIN': { symbol: 'JIOFIN', lotSize: 2000, sector: 'Financial Services' },
  'JUBLFOOD': { symbol: 'JUBLFOOD', lotSize: 1250, sector: 'FMCG' },
  'KEI': { symbol: 'KEI', lotSize: 200, sector: 'Capital Goods' },
  'KPITTECH': { symbol: 'KPITTECH', lotSize: 500, sector: 'IT' },
  'KALYANKJIL': { symbol: 'KALYANKJIL', lotSize: 1000, sector: 'Consumer Goods' },
  'KAYNES': { symbol: 'KAYNES', lotSize: 150, sector: 'Capital Goods' },
  'KFINTECH': { symbol: 'KFINTECH', lotSize: 500, sector: 'Financial Services' },
  'KOTAKBANK': { symbol: 'KOTAKBANK', lotSize: 400, sector: 'Banking' },
  'LTF': { symbol: 'LTF', lotSize: 4424, sector: 'Financial Services' },
  'LICHSGFIN': { symbol: 'LICHSGFIN', lotSize: 1000, sector: 'Financial Services' },
  'LTM': { symbol: 'LTM', lotSize: 150, sector: 'IT' },
  'LT': { symbol: 'LT', lotSize: 300, sector: 'Capital Goods' },
  'LAURUSLABS': { symbol: 'LAURUSLABS', lotSize: 1500, sector: 'Pharma' },
  'LICI': { symbol: 'LICI', lotSize: 300, sector: 'Financial Services' },
  'LODHA': { symbol: 'LODHA', lotSize: 400, sector: 'Realty' },
  'LUPIN': { symbol: 'LUPIN', lotSize: 425, sector: 'Pharma' },
  'M&M': { symbol: 'M&M', lotSize: 350, sector: 'Auto' },
  'MANAPPURAM': { symbol: 'MANAPPURAM', lotSize: 6000, sector: 'Financial Services' },
  'MANKIND': { symbol: 'MANKIND', lotSize: 250, sector: 'Pharma' },
  'MARICO': { symbol: 'MARICO', lotSize: 1200, sector: 'FMCG' },
  'MARUTI': { symbol: 'MARUTI', lotSize: 100, sector: 'Auto' },
  'MFSL': { symbol: 'MFSL', lotSize: 650, sector: 'Financial Services' },
  'MAXHEALTH': { symbol: 'MAXHEALTH', lotSize: 500, sector: 'Healthcare' },
  'MAZDOCK': { symbol: 'MAZDOCK', lotSize: 200, sector: 'Capital Goods' },
  'MOTILALOFS': { symbol: 'MOTILALOFS', lotSize: 400, sector: 'Financial Services' },
  'MPHASIS': { symbol: 'MPHASIS', lotSize: 200, sector: 'IT' },
  'MCX': { symbol: 'MCX', lotSize: 400, sector: 'Financial Services' },
  'MUTHOOTFIN': { symbol: 'MUTHOOTFIN', lotSize: 550, sector: 'Financial Services' },
  'NBCC': { symbol: 'NBCC', lotSize: 3000, sector: 'Realty' },
  'NHPC': { symbol: 'NHPC', lotSize: 4500, sector: 'Energy' },
  'NMDC': { symbol: 'NMDC', lotSize: 4500, sector: 'Metals' },
  'NTPC': { symbol: 'NTPC', lotSize: 3000, sector: 'Energy' },
  'NATIONALUM': { symbol: 'NATIONALUM', lotSize: 3750, sector: 'Metals' },
  'NESTLEIND': { symbol: 'NESTLEIND', lotSize: 400, sector: 'FMCG' },
  'NAM-INDIA': { symbol: 'NAM-INDIA', lotSize: 1100, sector: 'Financial Services' },
  'NUVAMA': { symbol: 'NUVAMA', lotSize: 100, sector: 'Financial Services' },
  'OBEROIRLTY': { symbol: 'OBEROIRLTY', lotSize: 350, sector: 'Realty' },
  'ONGC': { symbol: 'ONGC', lotSize: 3850, sector: 'Energy' },
  'OIL': { symbol: 'OIL', lotSize: 1800, sector: 'Energy' },
  'PAYTM': { symbol: 'PAYTM', lotSize: 800, sector: 'Financial Services' },
  'OFSS': { symbol: 'OFSS', lotSize: 125, sector: 'IT' },
  'POLICYBZR': { symbol: 'POLICYBZR', lotSize: 450, sector: 'Financial Services' },
  'PGEL': { symbol: 'PGEL', lotSize: 200, sector: 'Capital Goods' },
  'PIIND': { symbol: 'PIIND', lotSize: 250, sector: 'Chemicals' },
  'PNBHOUSING': { symbol: 'PNBHOUSING', lotSize: 800, sector: 'Financial Services' },
  'PAGEIND': { symbol: 'PAGEIND', lotSize: 15, sector: 'Consumer Goods' },
  'PATANJALI': { symbol: 'PATANJALI', lotSize: 450, sector: 'FMCG' },
  'PERSISTENT': { symbol: 'PERSISTENT', lotSize: 175, sector: 'IT' },
  'PETRONET': { symbol: 'PETRONET', lotSize: 3000, sector: 'Energy' },
  'PIDILITIND': { symbol: 'PIDILITIND', lotSize: 250, sector: 'Consumer Goods' },
  'POLYCAB': { symbol: 'POLYCAB', lotSize: 150, sector: 'Capital Goods' },
  'PFC': { symbol: 'PFC', lotSize: 3875, sector: 'Financial Services' },
  'POWERGRID': { symbol: 'POWERGRID', lotSize: 3600, sector: 'Energy' },
  'PREMIERENE': { symbol: 'PREMIERENE', lotSize: 1000, sector: 'Energy' },
  'PRESTIGE': { symbol: 'PRESTIGE', lotSize: 600, sector: 'Realty' },
  'PNB': { symbol: 'PNB', lotSize: 8000, sector: 'Banking' },
  'RBLBANK': { symbol: 'RBLBANK', lotSize: 2500, sector: 'Banking' },
  'RECLTD': { symbol: 'RECLTD', lotSize: 2000, sector: 'Financial Services' },
  'RVNL': { symbol: 'RVNL', lotSize: 2000, sector: 'Capital Goods' },
  'RELIANCE': { symbol: 'RELIANCE', lotSize: 250, sector: 'Energy' },
  'SBICARD': { symbol: 'SBICARD', lotSize: 800, sector: 'Financial Services' },
  'SBILIFE': { symbol: 'SBILIFE', lotSize: 375, sector: 'Financial Services' },
  'SHREECEM': { symbol: 'SHREECEM', lotSize: 25, sector: 'Cement' },
  'SRF': { symbol: 'SRF', lotSize: 375, sector: 'Chemicals' },
  'SAMMAANCAP': { symbol: 'SAMMAANCAP', lotSize: 4000, sector: 'Financial Services' },
  'MOTHERSON': { symbol: 'MOTHERSON', lotSize: 5000, sector: 'Auto' },
  'SHRIRAMFIN': { symbol: 'SHRIRAMFIN', lotSize: 300, sector: 'Financial Services' },
  'SIEMENS': { symbol: 'SIEMENS', lotSize: 125, sector: 'Capital Goods' },
  'SOLARINDS': { symbol: 'SOLARINDS', lotSize: 100, sector: 'Chemicals' },
  'SONACOMS': { symbol: 'SONACOMS', lotSize: 1000, sector: 'Auto' },
  'SBIN': { symbol: 'SBIN', lotSize: 1500, sector: 'Banking' },
  'SAIL': { symbol: 'SAIL', lotSize: 8000, sector: 'Metals' },
  'SUNPHARMA': { symbol: 'SUNPHARMA', lotSize: 700, sector: 'Pharma' },
  'SUPREMEIND': { symbol: 'SUPREMEIND', lotSize: 200, sector: 'Consumer Goods' },
  'SUZLON': { symbol: 'SUZLON', lotSize: 10000, sector: 'Energy' },
  'SWIGGY': { symbol: 'SWIGGY', lotSize: 1000, sector: 'Services' },
  'TATACONSUM': { symbol: 'TATACONSUM', lotSize: 900, sector: 'FMCG' },
  'TVSMOTOR': { symbol: 'TVSMOTOR', lotSize: 350, sector: 'Auto' },
  'TCS': { symbol: 'TCS', lotSize: 175, sector: 'IT' },
  'TATAELXSI': { symbol: 'TATAELXSI', lotSize: 100, sector: 'IT' },
  'TMPV': { symbol: 'TMPV', lotSize: 500, sector: 'Auto' },
  'TATAPOWER': { symbol: 'TATAPOWER', lotSize: 1350, sector: 'Energy' },
  'TATASTEEL': { symbol: 'TATASTEEL', lotSize: 5500, sector: 'Metals' },
  'TECHM': { symbol: 'TECHM', lotSize: 600, sector: 'IT' },
  'FEDERALBNK': { symbol: 'FEDERALBNK', lotSize: 5000, sector: 'Banking' },
  'INDHOTEL': { symbol: 'INDHOTEL', lotSize: 1000, sector: 'Services' },
  'PHOENIXLTD': { symbol: 'PHOENIXLTD', lotSize: 400, sector: 'Realty' },
  'TITAN': { symbol: 'TITAN', lotSize: 175, sector: 'Consumer Goods' },
  'TORNTPHARM': { symbol: 'TORNTPHARM', lotSize: 500, sector: 'Pharma' },
  'TRENT': { symbol: 'TRENT', lotSize: 400, sector: 'Retail' },
  'TIINDIA': { symbol: 'TIINDIA', lotSize: 125, sector: 'Capital Goods' },
  'UNOMINDA': { symbol: 'UNOMINDA', lotSize: 400, sector: 'Auto' },
  'UPL': { symbol: 'UPL', lotSize: 1300, sector: 'Chemicals' },
  'ULTRACEMCO': { symbol: 'ULTRACEMCO', lotSize: 100, sector: 'Cement' },
  'UNIONBANK': { symbol: 'UNIONBANK', lotSize: 5000, sector: 'Banking' },
  'UNITDSPR': { symbol: 'UNITDSPR', lotSize: 700, sector: 'FMCG' },
  'VBL': { symbol: 'VBL', lotSize: 600, sector: 'FMCG' },
  'VEDL': { symbol: 'VEDL', lotSize: 2300, sector: 'Metals' },
  'VMM': { symbol: 'VMM', lotSize: 1000, sector: 'Retail' },
  'IDEA': { symbol: 'IDEA', lotSize: 80000, sector: 'Telecom' },
  'VOLTAS': { symbol: 'VOLTAS', lotSize: 600, sector: 'Consumer Durables' },
  'WAAREEENER': { symbol: 'WAAREEENER', lotSize: 500, sector: 'Energy' },
  'WIPRO': { symbol: 'WIPRO', lotSize: 1500, sector: 'IT' },
  'YESBANK': { symbol: 'YESBANK', lotSize: 12000, sector: 'Banking' },
  'ZYDUSLIFE': { symbol: 'ZYDUSLIFE', lotSize: 900, sector: 'Pharma' },
};

export const FNO_SYMBOLS = Object.keys(FNO_DATA);
